# Generated by Django 5.1.1 on 2024-10-29 21:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('id_centro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estudios.estudio')),
            ],
            options={
                'db_table': 'centro',
            },
        ),
        migrations.CreateModel(
            name='LabAdmin',
            fields=[
                ('id_lab_admin', models.AutoField(primary_key=True, serialize=False)),
                ('centro_trabaja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lab_admin.centro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lab_admin',
            },
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id_presupuesto', models.AutoField(primary_key=True, serialize=False)),
                ('estudio', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='estudios.estudio')),
            ],
            options={
                'db_table': 'presupuestos',
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id_turno', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('numero', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudios.estudio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'turno',
            },
        ),
    ]
