# Generated by Django 5.1.1 on 2024-10-29 21:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('id_enfermedad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'enfermedad',
            },
        ),
        migrations.CreateModel(
            name='SampleSet',
            fields=[
                ('id_sample_set', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_muestras', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('fecha_envio', models.DateField(blank=True, null=True)),
                ('fecha_devolucion', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sample_sets',
            },
        ),
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id_estudio', models.AutoField(primary_key=True, serialize=False)),
                ('id_interno', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('tipo_estudio', models.CharField(max_length=100)),
                ('resultado', models.TextField()),
                ('estado', models.CharField(choices=[('IN', 'Iniciado'), ('PR', 'Presupuestado'), ('PA', 'Pagado'), ('TC', 'Turno Confirmado'), ('RE', 'Realizada'), ('CE', 'Centralizada'), ('EE', 'Enviada al Exterior'), ('FI', 'Finalizado')], default='IN', max_length=2)),
                ('patologia', models.CharField(max_length=200)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pacientes.paciente')),
                ('sample_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='estudios.sampleset')),
            ],
            options={
                'db_table': 'estudios',
            },
        ),
    ]
